parameters:
    queueId: ""
    sendTimeout: "^Lexide\\QueueBall\\ZeroMq\\SocketFactory::TIMEOUT_INFINITE^"

services:
    zmqContext:
        class: \ZMQContext

    socketFactory:
        class: Lexide\QueueBall\ZeroMq\SocketFactory
        arguments:
            - "@zmqContext"
            - "%sendTimeout%"

    zeroMqQueue:
        class: Lexide\QueueBall\ZeroMq\Queue
        arguments:
            - "@socketFactory"
            - "@lexide_queueball.messageFactory"
            - "%queueId%"

    lexide_queueball.defaultQueue:
        aliasOf: "@zeroMqQueue"
