parameters:
    queueId: ""
    sendTimeout: "-1" # -1 means wait infinitely

services:
    zmqContext:
        class: \ZMQContext

    socketFactory:
        class: Silktide\QueueBall\ZeroMq\SocketFactory
        arguments:
            - @zmqContext
            - %sendTimeout%

    zeroMqQueue:
        class: Silktide\QueueBall\ZeroMq\Queue
        arguments:
            - @socketFactory
            - @silktide_queueball.messageFactory
            - %queueId%

    silktide_queueball.defaultQueue:
        aliasOf: @zeroMqQueue